name: Bug Report
description: Something is not working right
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Before opening a new issue,** take a moment to search through the current open and closed issues to check if it already exists.

        ---

  - type: input
    id: asdasd
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.


  - type: dropdown
    id: browsers
    attributes:
      label: Regression?
      default: 0
      description: |
        Regression means that something used to work but no longer does.
        **PLEASE**, before continuing check if this bug is a regression or not, and if it is, we need you to bisect with the help of the wiki: https://wiki.hyprland.org/Crashes-and-Bugs/#bisecting-an-issue
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: "What went wrong?"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: "How can someone else reproduce the issue?"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Crash reports, logs, images, videos
      description: |
        Anything that can help. Please always ATTACH and not paste them.
        Logs can be found in $XDG_RUNTIME_DIR/hypr
        Crash reports are stored in ~/.cache/hyprland or $XDG_CACHE_HOME/hyprland

